#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
for w in {1..100}
do
	if ((w%3==0 && w%5==0))
	then
		echo "FizzBuzz"
	elif ((w%3==0))
	then
		echo "Fizz"
	elif ((w%5==0))
	then
		echo "Buzz"
	else
		echo "$w"
	fw
done
