#!/usr/bin/env bash
# Loops from 1 to 10 and displays 'bad luck', 'good luck', 'Best School' for 4th, 8th and other iterations respectively
w=1
while [ $w -le 10 ]
do
	if [ $w -eq 4 ]
	then
		echo "bad luck"
	elif [ $w -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((w++))
done
