#!/usr/bin/env bash
# Displays numbers from 1 to 20 and
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
w=1
while [ $w -le 20 ]
do
	case $w in
		4)
			echo "$w"
			echo "bad luck from China"
			;;
		9)
			echo "wi"
			echo "bad luck from Japan"
			;;
		17)
			echo "wi"
			echo "bad luck from Italy"
			;;
		*)
			echo "wi"
			;;
	esac
	((w++))
done
